#!/usr/bin/bash

#####
# postinst script
####

set -euo pipefail

# Declaration variables
meoListInstalledPkgs="/usr/lib/meo/library/info/list-installed-packages"
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"



### Enable and the service linked to the <<am-okay>> program, and do another actions . [tag0]

sudo systemctl enable am-okay-boot.service  &> /dev/null
sudo systemctl daemon-reload  &> /dev/null
sudo systemctl start am-okay-boot.service  &> /dev/null



# Add information about the package in these specific files
if [[ -e "$meoListInstalledPkgsPure" ]]
then

    if [[ ! ` cat $meoListInstalledPkgsPure | grep -w -- "am-okay" ` ]]
    then
        #
        sed -i "$ a am-okay : v(3.1.0)" "$meoListInstalledPkgsPure" 2> /dev/null
        sed -i -e "$ a ` echo -e "\e[32;1mam-okay\e[0m : \e[36;1mv(3.1.0)\e[0m" ` " "$meoListInstalledPkgs" 2> /dev/null
    fi
fi


# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null

exit 0

### End of [tag0]
