#!/usr/bin/bash

#####
# postinst script
####

set -euo pipefail

### Enable and the service linked to the <<am-okay>> program, and do another actions . [tag0]

sudo systemctl enable am-okay-boot.service  &> /dev/null
sudo systemctl daemon-reload  &> /dev/null
sudo systemctl start am-okay-boot.service  &> /dev/null


# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null

exit 0

### End of [tag0]
