#!/usr/bin/bash

#####
# postrm script
####

set -euo pipefail

# Declaration variables
meoListInstalledPkgs="/usr/lib/meo/library/info/list-installed-packages"
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"

if [[ -e "$meoListInstalledPkgsPure" ]]
then
    #
    sed -i "/am-okay/d" $meoListInstalledPkgsPure 2> /dev/null
    sed -i "/am-okay/d" $meoListInstalledPkgs 2> /dev/null
fi

