#!/usr/bin/bash

#####
# postinst script
####

set -euo pipefail



### Enable the service linked to the <<am-okay>> program, and do another actions -> start tag[0]

sudo systemctl enable am-okay-boot.service  &> /dev/null
sudo systemctl daemon-reload  &> /dev/null
sudo systemctl start am-okay-boot.service  &> /dev/null


# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null


### Enable the service linked to the <<am-okay>> program, and do another actions -> end tag[s0]
