#!/bin/bash
# postinst script for lumus
#

set -e

# For setting the service linked to the script that gives the proper permissions to the user(admin) at each boot

sudo systemctl enable at-boot.service  &> /dev/null
sudo systemctl daemon-reload
sudo systemctl start at-boot.service
echo "~"
echo ""
tput setaf 2; tput bold;echo "By Baldé ~" `tput sgr0` 2> /dev/null

exit 0
