#!/usr/bin/bash

#####
# prerm script
####

set -euo pipefail

# Declaration variables
meoListInstalledPkgs="/usr/lib/meo/library/info/list-installed-packages"
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"

if [[ -e "$meoListInstalledPkgsPure" ]]
then
    #
    sed -i "/vimizer/d" "$meoListInstalledPkgsPure" 2> /dev/null
    sed -i "/vimizer/d" "$meoListInstalledPkgs" 2> /dev/null
fi

