#!/usr/bin/bash

#####
# postinst script
####


set -euo pipefail



# Declaration variables
getTheDebProgram=""

getMngDebDirectory="/usr/lib/meo/library/packages-info/meo/deb"
getTmpCloneGit="/tmp/$USER/.meo/download-branch"
getBranch="meo"
getProgram="meo"
getURL="https://github.com/baldeuniversel/linux.git"



#
if [[ ! -e "$getMngDebDirectory" ]]
then
    #
    mkdir -p "$getMngDebDirectory" 2> /dev/null
else
    #
    rm -fr "$getMngDebDirectory" 2> /dev/null
    
    mkdir -p "$getMngDebDirectory" 2> /dev/null
fi

#
if [[ -e "$getTmpCloneGit" ]]
then
    
    rm -fr "$getTmpCloneGit" 2> /dev/null
else
    mkdir -p "$getTmpCloneGit" 2> /dev/null
fi


# Clone the branch
git clone --branch "$getBranch" --single-branch --depth 1 "$getURL" "$getTmpCloneGit/linux" 2> /dev/null

#
getTheDebProgram=` find "$getTmpCloneGit/linux" -name "$getProgram*.deb" -type f 2> /dev/null ` 

# Move the deb program
mv "$getTheDebProgram" "$getMngDebDirectory" 2> /dev/null



:   '
# Declaration variables
#
meoInfoDir="/usr/lib/meo/library/info"
meoListInstalledPkgs="/usr/lib/meo/library/info/list-installed-packages"
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"



#
if [[ ! -e "$meoInfoDir" ]]
then
    #
    mkdir -p "$meoInfoDir" 2> /dev/null
fi


#
if [[ -e "$meoListInstalledPkgsPure" ]] && [[ -s "$meoListInstalledPkgsPure" ]]
then

    #
    if [[ ! ` cat "$meoListInstalledPkgsPure" | grep -w -- "meo" ` ]]
    then

        # Add `meo` program as an installed package
        sed -i -e "$ a ` echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.7)\e[0m" ` " $meoListInstalledPkgs
        sed -i "$ a meo : v(1.1.7)" $meoListInstalledPkgsPure
    
    elif [[ ` cat "$meoListInstalledPkgsPure" | grep -w -- "meo" ` ]]
    then
        
        #
        getLineMeoString=` cat "$meoListInstalledPkgsPure" | grep -wn "meo" | cut -d ":" -f 1 `

        # Replace the old version of the `meo` program
        sed -i -e "$getLineMeoString s/...*/` echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.7)\e[0m" `/" $meoListInstalledPkgs 2> /dev/null
        sed -i -e "$getLineMeoString s/...*/` echo -e "meo : v(1.1.7)" `/" $meoListInstalledPkgsPure 2> /dev/null
    fi

elif [[ -e "$meoListInstalledPkgsPure" ]] && [[ ! -s "$meoListInstalledPkgsPure" ]]
then
    # Add `meo` program as an installed package
    echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.7)\e[0m" >> $meoListInstalledPkgs
    echo -e "meo : v(1.1.7)" >> $meoListInstalledPkgsPure

elif [[ ! -e "$meoListInstalledPkgsPure" ]]
then

    # Add `meo` program as an installed package
    echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.7)\e[0m" > $meoListInstalledPkgs
    echo -e "meo : v(1.1.7)" > $meoListInstalledPkgsPure
fi

    '

# Remove the `tmp/..` directory
if [[ -e "$getTmpCloneGit" ]]
then
    # 
    rm -fr "$getTmpCloneGit" 2> /dev/null
fi



# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null
