#!/usr/bin/bash

#####
# postinst script
####

set -euo pipefail

# Declaration variables
meoListInstalledPkgs="/usr/lib/meo/library/info/list-installed-packages"
meoListInstalledPkgsPure="/usr/lib/meo/library/info/list-installed-packages-pure"

meoInfoDir="/usr/lib/meo/library/info"



#
if [[ ! -e "$meoInfoDir" ]]
then
    #
    mkdir -p "$meoInfoDir" 2> /dev/null
fi


#
if [[ -e "$meoListInstalledPkgsPure" ]] && [[ -s "$meoListInstalledPkgsPure" ]]
then

    #
    if [[ ! ` cat "$meoListInstalledPkgsPure" | grep -w -- "meo" ` ]]
    then

        # Add `meo` program as an installed package
        sed -i -e "$ a ` echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.6)\e[0m" ` " $meoListInstalledPkgs
        sed -i "$ a meo : v(1.1.6)" $meoListInstalledPkgsPure
    
    elif [[ ` cat "$meoListInstalledPkgsPure" | grep -w -- "meo" ` ]]
    then
        
        #
        getLineMeoString=` cat "$meoListInstalledPkgsPure" | grep -wn "meo" | cut -d ":" -f 1 `

        # Replace the old version of the `meo` program
        sed -i -e "$getLineMeoString s/...*/` echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.6)\e[0m" `/" $meoListInstalledPkgs 2> /dev/null
        sed -i -e "$getLineMeoString s/...*/` echo -e "meo : v(1.1.6)" `/" $meoListInstalledPkgsPure 2> /dev/null
    fi

elif [[ -e "$meoListInstalledPkgsPure" ]] && [[ ! -s "$meoListInstalledPkgsPure" ]]
then
readme
    # Add `meo` program as an installed package
    echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.6)\e[0m" >> $meoListInstalledPkgs
    echo -e "meo : v(1.1.6)" >> $meoListInstalledPkgsPure

elif [[ ! -e "$meoListInstalledPkgsPure" ]]
then

    # Add `meo` program as an installed package
    echo -e "\e[32;1mmeo\e[0m : \e[36;1mv(1.1.6)\e[0m" >> $meoListInstalledPkgs
    echo -e "meo : v(1.1.6)" >> $meoListInstalledPkgsPure
fi



# Just to print the name of the author
echo ""
echo ""
echo "~"

tput setaf 6; tput bold; echo "By Baldé ~" `tput sgr0` 2> /dev/null

exit 0
